# Generated by Django 4.2.5 on 2023-09-13 05:58

import Context.preference.enum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PreferenceEntity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.CharField(max_length=32, verbose_name="내용")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (
                                Context.preference.enum.PreferenceType["MBTI"],
                                Context.preference.enum.PreferenceType["MBTI"],
                            ),
                            (
                                Context.preference.enum.PreferenceType["keyword"],
                                Context.preference.enum.PreferenceType["keyword"],
                            ),
                            (
                                Context.preference.enum.PreferenceType["growth"],
                                Context.preference.enum.PreferenceType["growth"],
                            ),
                            (
                                Context.preference.enum.PreferenceType["habit"],
                                Context.preference.enum.PreferenceType["habit"],
                            ),
                            (
                                Context.preference.enum.PreferenceType["date_style"],
                                Context.preference.enum.PreferenceType["date_style"],
                            ),
                        ],
                        max_length=32,
                        verbose_name="기호",
                    ),
                ),
                ("order", models.PositiveIntegerField(null=True, verbose_name="노출 순위")),
            ],
            options={
                "verbose_name": "[preference] 기호",
                "verbose_name_plural": "[preference] 기호",
                "db_table": "preference",
            },
        ),
        migrations.CreateModel(
            name="MemberPreferenceAggregate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (
                                Context.preference.enum.PreferenceType["MBTI"],
                                Context.preference.enum.PreferenceType["MBTI"],
                            ),
                            (
                                Context.preference.enum.PreferenceType["keyword"],
                                Context.preference.enum.PreferenceType["keyword"],
                            ),
                            (
                                Context.preference.enum.PreferenceType["growth"],
                                Context.preference.enum.PreferenceType["growth"],
                            ),
                            (
                                Context.preference.enum.PreferenceType["habit"],
                                Context.preference.enum.PreferenceType["habit"],
                            ),
                            (
                                Context.preference.enum.PreferenceType["date_style"],
                                Context.preference.enum.PreferenceType["date_style"],
                            ),
                        ],
                        max_length=32,
                        verbose_name="기호",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_preference",
                        to="preference.preferenceentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "[member_preference] 멤버 기호",
                "verbose_name_plural": "[member_preference] 멤버 기호",
                "db_table": "member_preference",
            },
        ),
    ]
