# Generated by Django 4.2.5 on 2023-09-13 05:58

import Context.review.domain.member_review
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberReviewAggregate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("file", models.ImageField(upload_to=Context.review.domain.member_review.get_s3_file_path)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("face", "얼굴"),
                            ("body", "체형"),
                            ("income", "소득"),
                            ("car", "차"),
                            ("house", "집"),
                            ("asset", "자산"),
                            ("compony", "직장"),
                            ("education", "교육"),
                        ],
                        max_length=16,
                        verbose_name="심사 타입",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("approved", "인증 완료"), ("rejected", "인증 불가"), ("under_review", "심사 중")],
                        max_length=16,
                        verbose_name="심사 상태",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="member_storage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "[member_review] 멤버 심사 심사",
                "verbose_name_plural": "[member_review] 멤버 심사",
                "db_table": "member_review",
            },
        ),
    ]
