# Generated by Django 4.2.5 on 2023-09-13 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressLevel1Entity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=16, verbose_name="도/광역시")),
                ("order", models.PositiveIntegerField(null=True, verbose_name="노출 순위")),
            ],
            options={
                "verbose_name": "[address_level1] 1단계 주소 정보 - 도/광역시/특별시",
                "verbose_name_plural": "[address_level1] 1단계 주소 정보 - 도/광역시/특별시",
                "db_table": "address_level1",
            },
        ),
        migrations.CreateModel(
            name="AddressLevel2Aggregate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=16, verbose_name="시")),
                ("order", models.PositiveIntegerField(null=True, verbose_name="노출 순위")),
                (
                    "level1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level2",
                        to="address.addresslevel1entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "[address_level2] 2단계 주소 정보 - 일반시/구",
                "verbose_name_plural": "[address_level2] 2단계 주소 정보 - 도/광역시/특별시",
                "db_table": "address_level2",
            },
        ),
        migrations.CreateModel(
            name="MemberPlayingAddressAggregate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "level1_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playing_level1_address",
                        to="address.addresslevel1entity",
                    ),
                ),
                (
                    "level2_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playing_level2_address",
                        to="address.addresslevel2aggregate",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playing_address",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "[member_playing_address] 사용자 활동 지역",
                "verbose_name_plural": "[member_playing_address] 사용자 활동 지역",
                "db_table": "member_playing_address",
                "index_together": {("level1_address", "level2_address")},
            },
        ),
        migrations.CreateModel(
            name="MemberLivingAggregate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "level1_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="living_level1_address",
                        to="address.addresslevel2aggregate",
                    ),
                ),
                (
                    "level2_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="living_level2_address",
                        to="address.addresslevel2aggregate",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="living_address",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "[member_ling_address] 사용자 계정",
                "verbose_name_plural": "[member_ling_address] 사용자 계정",
                "db_table": "member_ling_address",
                "index_together": {("level1_address", "level2_address")},
            },
        ),
    ]
