# Generated by Django 4.2.5 on 2023-09-13 05:54

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemberEntity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("name", models.CharField(max_length=32, verbose_name="본명")),
                ("gender", models.CharField(choices=[("F", "여자"), ("M", "남자")], max_length=4, verbose_name="성별")),
                (
                    "nickname",
                    models.CharField(
                        help_text="Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=30,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="닉네임",
                    ),
                ),
                (
                    "birth_year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1800),
                            django.core.validators.MaxValueValidator(2200),
                        ],
                        verbose_name="출생 연도",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "가입만 완료"),
                            ("under_review", "심사중"),
                            ("recommend_off", "추천제외 상태"),
                            ("active", "모든 심사 완료"),
                            ("inactive", "탈퇴 상태"),
                        ],
                        max_length=32,
                        verbose_name="성별",
                    ),
                ),
                ("last_access", models.DateTimeField(default=django.utils.timezone.now, verbose_name="마지막 접근 시간")),
                ("is_staff", models.BooleanField(default=False, verbose_name="스태프 여부")),
                ("is_superuser", models.BooleanField(default=False, verbose_name="슈퍼유저 여부")),
            ],
            options={
                "verbose_name": "[member] 사용자 계정",
                "verbose_name_plural": "[member] 사용자 계정",
                "db_table": "member",
                "index_together": {("gender", "birth_year", "status")},
            },
        ),
    ]
