# Generated by Django 4.2.5 on 2023-09-13 11:39

import Context.member.enum
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberentity",
            name="gender",
            field=models.CharField(
                choices=[(Context.member.enum.Gender["female"], "여자"), (Context.member.enum.Gender["male"], "남자")],
                max_length=4,
                verbose_name="성별",
            ),
        ),
        migrations.AlterField(
            model_name="memberentity",
            name="status",
            field=models.CharField(
                choices=[
                    (Context.member.enum.MemberStatus["registered"], "가입만 완료"),
                    (Context.member.enum.MemberStatus["under_review"], "심사중"),
                    (Context.member.enum.MemberStatus["recommend_off"], "추천제외 상태"),
                    (Context.member.enum.MemberStatus["active"], "모든 심사 완료"),
                    (Context.member.enum.MemberStatus["inactive"], "탈퇴 상태"),
                ],
                max_length=32,
                verbose_name="성별",
            ),
        ),
    ]
